name: tracker
description: Tracker - Safety way to stalk your child.
publish_to: none
version: 1.0.0+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.0
    provider: ^4.3.2+3
    after_init: 0.1.2
    google_fonts: 1.1.1
    shared_preferences: 0.5.12+4
    http: 0.12.2
    equatable: 1.2.5
    flutter_google_maps: ^4.0.0
    geolocator: ^6.1.13
    google_maps_webservice: ^0.0.19

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/img/
        